### ISSUE TITLE
Cannot import the package in meteor 

### ISSUE THREAD

**Issue by a-magdy** [nlhuykhang/ddp-rate-limiter-mixin#1]
I tried using the package with meteor, but it gave me the error:

```
Error: Can't find npm module 'ddp-rate-limiter-mixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```
This happens also with the example in the repo, tried installing the package with npm i -S, and meteor install, both gave me the same error!

then I tried importing the file directly from node_modules/ddp-rate-limiter-mixin/dist/index but it gave me this error:

```
W20170510-17:43:04.615(2)? (STDERR) packages/modules.js:336
W20170510-17:43:04.616(2)? (STDERR) import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
W20170510-17:43:04.616(2)? (STDERR) ^^^^^^
W20170510-17:43:04.616(2)? (STDERR)
W20170510-17:43:04.616(2)? (STDERR) SyntaxError: Unexpected reserved word
W20170510-17:43:04.616(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
```

And it worked when I imported the rate-limiter file directly:

```
import { RateLimiterMixin } from '../node_modules/ddp-rate-limiter-mixin/dist/rate-limiter';
```
And thank you for your effort :)

**Comment by nlhuykhang** [comment]
I just published a new version. It will solve this issue, please try this new version.

**Comment by Hanley1** [comment]
Happening for me as well. v 1.1.7

**Comment by nlhuykhang** [comment]
@Hanley1 What error message did you see?

**Comment by Hanley1** [comment]
Thanks for the quick response. Here's the error:

```
/Users/Joe/Developer/audible_genius/node_modules/ddp-rate-limiter-mixin/dist/index.js:3
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Joe/Developer/audible_genius/node_modules/ddp-rate-limiter-mixin/index.js:1:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by Hanley1** [comment]
Any ideas?

**Comment by nlhuykhang** [comment]
@Hanley1 sorry, I missed this issue. Turn out there was a problem with the publish script. I fixed it and publish a new version v1.1.8. Please try again.

**Comment by Hanley1** [comment]
Thanks, it now imports. However, when I add the mixin to a validated method, I get a new error:

```
modules.js?hash=8c9ad9c154dd097134750179df65541f25e7883f:1158 Uncaught ReferenceError: DDPRateLimiter is not defined
    at RateLimiterMixin (modules.js?hash=8c9ad9c154dd097134750179df65541f25e7883f:1158)
    at validated-method.js:105
    at Array.forEach (<anonymous>)
    at applyMixins (validated-method.js:104)
    at new ValidatedMethod (validated-method.js:9)
    at contactMethods.js (contactMethods.js:75)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at app.js?hash=235dea345a1758e866b2415fc27f0306b34170a1:69678
```

Referring to this bit of code in the module:

```
DDPRateLimiter.addRule({
type: 'method', 
name: name, 
userId: userId, 
connectionId: connectionId,  
clientAddress: clientAddress}, numRequests, timeInterval, callback);
```

Here's how I'm calling it:

```
import { ValidatedMethod } from 'meteor/mdg:validated-method';
import { RateLimiterMixin } from 'ddp-rate-limiter-mixin';

const foo = new ValidatedMethod({
  name: 'foo',
  mixins: [RateLimiterMixin],
  rateLimit: {
    numRequests: 5,
    timeInterval: 5000,
  },
  validate: null,
  run() {
    // ...
  }
});
```

I have DDPRateLimiter installed and am using in another part of my app to rate limit subscriptions without issue.

**Comment by nlhuykhang** [comment]
Is this error on your client or server?

**Comment by Hanley1** [comment]
Client. This code is located in my lib folder.

**Comment by nlhuykhang** [comment]
That makes sense now, because `DDPRateLimiter` is server-only code. I updated the code to not apply the mixin on client. You will not encounter this error with the new version.

**Comment by Hanley1** [comment]
Works great now. Thanks for your quick responses and quality work!
